### ISSUE TITLE
Update requirements to use msgpack (not msgpack-python)

### ISSUE THREAD

**Issue by jakirkham** [intake/intake-xarray#102]
Currently `intake-xarray` lists `msgpack-python` as a requirement. However [upstream renamed this to `msgpack`]( https://github.com/msgpack/msgpack-python#pypi-package-name ). Would be good to have the requirement updated here accordingly

https://github.com/intake/intake-xarray/blob/aceb7315bded05793ce3c047070df9ac092ba375/setup.py#L12-L13

cc @jrbourbeau @martindurant @weiji14

**Comment by martindurant** [comment]
OK, so what does this do with the pypi version, do I need to make a new one?

**Comment by weiji14** [comment]
Probably easiest to do the `msgpack-python` to `msgpack` rename, tag a new version for `intake-xarray` and push a new PyPI release. The alternative (yanking the intake-xarray v0.4.2 release from PyPI and republishing) is much harder, and probably not a good idea.

**Comment by weiji14** [comment]
Oh, and we should probably tag the release as v0.5.0 because the minimum version of Python was bumped from Python 3.6 to Python 3.7 (due to a minimum xarray version of 0.17.0, up from 0.12.0) in #101. As per [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html#implementation):

> Minimum Python and NumPy version support should be adjusted upward on every major and minor release, but never on a patch release.

**Comment by martindurant** [comment]
fine, done
