### ISSUE TITLE
fix upstream

### ISSUE THREAD

**Issue by raybellwaves** [intake/intake-xarray#119]
The attribute error seems simple enough, not sure about the import error. Do you think you can fix these here?

__Originally posted by @martindurant in https://github.com/intake/intake-xarray/pull/118#issuecomment-1136036806__

**Comment by aaronspring** [comment]
they find the same error [here](https://github.com/rasterio/rasterio/issues/2381#issuecomment-1021314045)

**Comment by raybellwaves** [comment]
Copying CI errors from https://github.com/intake/intake-xarray/runs/6648327312?check_suite_focus=true

```
________________________________ test_discovery ________________________________

    def test_discovery():
        with pytest.warns(None) as record:
>           registry = intake.source.discovery.autodiscover()
E           AttributeError: module 'intake.source.discovery' has no attribute 'autodiscover'

intake_xarray/tests/test_discovery.py:7: AttributeError
```

and rasterio stuff...

**Comment by raybellwaves** [comment]
The rasterio could be discussed here: https://github.com/intake/intake-xarray/issues/87

**Comment by martindurant** [comment]
So close this and focus on the rasterio discussion?
