### ISSUE TITLE
Update package?

### ISSUE THREAD

**Issue by kthyng** [intake/intake-xarray#128]
Would it be possible for intake-xarray to be updated on PyPI and conda-forge? I have packages relying on code that has joined intake-xarray since the last release and it's getting tricky to make my packages easily installable.

(This is true for both intake and intake-xarray, hence my duplicate issues: https://github.com/intake/intake/issues/683)

**Comment by kthyng** [comment]
I'd be happy to help with the release! I see some instructions here for PyPI anyway: https://intake-xarray.readthedocs.io/en/latest/contributing.html#id2

**Comment by martindurant** [comment]
Done

**Comment by kthyng** [comment]
Thank you!
