### ISSUE TITLE
What happened on xarray's document?

### ISSUE THREAD

**Issue by forestbat** [intake/intake-xarray#140]
https://intake.readthedocs.io/en/latest/plugin-directory.html
Serveral months ago there are many drivers on this webpage and I can find driver which I need quickly.
However the table which contains drivers disappeared now, and I can't run intake.open_textfiles or intake.open_json correctly.
So what happened to intake and its drivers, documents?

**Comment by martindurant** [comment]
At the top of the current documentation https://intake.readthedocs.io/en/latest/ we describe how Intake Take2 is a major break with intake as it has been so far. You are welcome to pin to version<2, and we do aim for compatibility, but we are still ironing out details. The docs still contain all the V1 pages, but only if you navigate to them.

- firstly: thanks for letting me know, I wasn't aware that the plugins page doc build had broken.

- secondly: I'm not certain why intake.source.textfiles.TextFilesSource and intake.source.jsonfiles.JSONFileSource are not being pulled in at the top level, but they do still exist and still work. I will fix this.

- thirdly, you may be interested in formulating your process with V2 now that it's here. For example:

```
url = "prot://path/to/file.text"
data = intake.readers.datatypes.Text(url)
reader = intake.readers.readers.FileBytes(data)
reader.read()
```
... but there are various methods to figure out how best to represent and read your dataset, as well as many different readers for "text" (e.g., spark, ray, keras...) depending on your needs.

We are working hard to smothe all the kinks!

**Comment by forestbat** [comment]
```
url = "s3://datasets-interim/camels_cc/basin_mean_forcing/61239_lump_era5_land_forcing.txt"
data = itk.readers.datatypes.Text(url, storage_options=storage_option)
reader = itk.readers.readers.FileByteReader(data)
reader.read()
```
It's successful, thank for your reply.
