### ISSUE TITLE
intake v2 overrides `zarr` driver alias

### ISSUE THREAD

**Issue by rafa-guedes** [intake/intake-xarray#144]
In intake v2, the alias for the `intake.source.zarr` driver was renamed from [ndzarr](https://github.com/intake/intake/blob/0.7.0/setup.py#L55) to [zarr](https://github.com/intake/intake/blob/master/pyproject.toml#L65). This conflicts with the [intake-xarray's](https://github.com/intake/intake-xarray/blob/master/setup.py#L29) version so the latter can no longer be defined using the alias in the catalog. Would it be a good idea to redefine the alias for either the intake or the intake_xarray version?

**Comment by martindurant** [comment]
Ah, OK, totally reasonable to rename the V1 zarr source in the V2 codebase to what it used to be.

**Comment by rafa-guedes** [comment]
Done in https://github.com/intake/intake/pull/831
