### ISSUE TITLE
Incompatible with dask 2.2.0.

### ISSUE THREAD

**Issue by danielballan** [intake/intake-xarray#48]
The object `get_fs` was removed from `dask.bytes.core` in dask's v2.2.0 release. We use it for example in `xzarr.py`

https://github.com/intake/intake-xarray/blob/master/intake_xarray/xzarr.py#L28

Example failure from an intake-bluesky build: https://travis-ci.org/bluesky/intake-bluesky/jobs/567421853#L444

**Comment by martindurant** [comment]
Can you please check with https://github.com/intake/intake-xarray/pull/46 ? If that works, I'll merge and release.

**Comment by danielballan** [comment]
Oh, great! Tested against `intake@master` and `intake-xarray@master`. Works.
