### ISSUE TITLE
Conda ClobberError

### ISSUE THREAD

**Issue by alimanfoo** [intake/intake-xarray#49]
Installing intake-xarray alongside a bunch of other packages, I'm getting:

```
[ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::json5-0.8.5-py_0, conda-forge::intake-xarray-0.3.1-py_0
  path: 'lib/python3.6/site-packages/tests/__init__.py'

, ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::json5-0.8.5-py_0, conda-forge::intake-xarray-0.3.1-py_0
  path: 'lib/python3.6/site-packages/tests/__pycache__/__init__.cpython-36.pyc'

]
```

I think it's relatively harmless but might be worth resolving, I guess it's to do with the tests package not being within intake package somehow.

**Comment by martindurant** [comment]
Thanks for pointing that out. Possible remedies:

- move tests folder into the package
- remove tests from MANIFEST
- remove tests within conda script

**Comment by martindurant** [comment]
@jsignell , pinging you, in case I don't get to this before you have time again. I suppose the first suggestion, above, is the most typical.

**Comment by jsignell** [comment]
Yes I think the first is the best. I don't know if there are any implications but I can open a PR to get it started.
