### ISSUE TITLE
passing / overriding kwargs when opening datasets

### ISSUE THREAD

**Issue by rabernat** [intake/intake-xarray#52]
I would like to be able to optionally override or pass additional keyword arguments to xarray when opening datasets from intake.

Consider our cannonical example

```python
import fsspec
import xarray as xr
mapper = fsspec.get_mapper("gcs://pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt")
ds = xr.open_zarr(mapper, consolidated=True)
```

There are many options I might want to pass to `open_zarr`. For example
- `chunks=None`: skip auto chunking
- `decode_cf=False`: don't decode cf
- etc. etc.

If I open this file via intake:
```python
import intake
cat = intake.Catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
ds = cat["sea_surface_height"].to_dask()
```

there is no way to choose any of those options.

Could we make `.to_dask()` (itself a strange syntax...why not `.to_xarray()`) accept arbitrary keyword arguments which are passed to the reader function?

**Comment by jsignell** [comment]
I also can't find where this is discussed in the docs. @rabernat is there a specific place where you'd expect it to be?

**Comment by martindurant** [comment]
Closing this as old, and we have plans to unify the "entry" and "source" classes to avoid the confusion.
