### ISSUE TITLE
BUG open Yaml file causes  Subclass should implement _get_partition()

### ISSUE THREAD

**Issue by NickMortimer** [intake/intake-xarray#58]
I'm trying to parameterise my notebooks to execute them using papermill things are going well but I'm getting different behaviour from opening a list of nc files vs opening from a catalogue yaml file

open from list of files (I prefer list of file to *.nc because I'm trying to record what files have been used)

```
cat = intake.open_netcdf(glob.glob('./data/sst/*.nc'),**{'concat_dim':'time', 'xarray_kwargs':{'combine':'by_coords'}})
cat.read_chunked()

<xarray.Dataset>
Dimensions:  (lat: 89, lon: 180, time: 684)
Coordinates:
  * lon      (lon) float32 0.0 2.0 4.0 6.0 8.0 ... 350.0 352.0 354.0 356.0 358.0
  * lat      (lat) float32 -88.0 -86.0 -84.0 -82.0 -80.0 ... 82.0 84.0 86.0 88.0
  * time     (time) datetime64[ns] 1960-01-15 1960-02-15 ... 2016-12-15
Data variables:
    sst      (time, lat, lon) float32 dask.array<chunksize=(12, 89, 180), meta=np.ndarray>
Attributes:
    Conventions:  IRIDL
    source:       https://iridl.ldeo.columbia.edu/SOURCES/.NOAA/.NCDC/.ERSST/...
    history:      extracted and cleaned by Ryan Abernathey for Research Compu...
```

Then save it to a catalogue to use late

```
with open("sst.yml", "w") as text_file:
    text_file.write(cat.yaml())
```

cat = intake.open_catalog("sst.yml")
cat.read()

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-77-1ea2fb39759c> in <module>
----> 1 cat.read()

C:\ProgramData\Anaconda3\envs\dev\lib\site-packages\intake\source\base.py in read(self)
    178         """Load entire dataset into a container and return it"""
    179         if not self.partition_access or self.npartitions == 1:
--> 180             return self._get_partition(0)
    181         else:
    182             raise NotImplementedError

C:\ProgramData\Anaconda3\envs\dev\lib\site-packages\intake\source\base.py in _get_partition(self, i)
    103         This function will never be called with an out-of-range value for i.
    104         """
--> 105         raise Exception('Subclass should implement _get_partition()')
    106 
    107     def _close(self):

Exception: Subclass should implement _get_partition()

How do I load netcdf files from a catalogue yaml file?

**Comment by martindurant** [comment]
You cannot "read" a catalog, because it doesn't store data, but stores entries. In your case, the entry is probably called "netcdf" (check `list(cat)`), and you should access it as `cat.netcdf`, and then do read or whatever else.

**Comment by NickMortimer** [comment]
Ok I see now thanks for the quick response!
