### ISSUE TITLE
intake_xarray and xarray.open_mzarr

### ISSUE THREAD

**Issue by Mikejmnez** [intake/intake-xarray#67]
Hi, 
I am working on a project that reads data from multiple zarr files. I have written a function to enable reading multiple zarr files on xarray (it works and I will submit a PR on xarray) and it would be incredibly helpful if intake_xarray can use this function. Without it, I would need to register individual intake_Catalog entries, one per file (files are distributed across several nodes). It would be great to have something like:
'
driver: zarr
args:
    urlpath: '/sciserver/filedb*/ocean/poseidon/LLC4320/*
    parallel: True
'
I can work on this, if people are not already working on this (conflicting work)

**Comment by martindurant** [comment]
(since the xarray PR is in progress, I suggest linking it here and closing this issue)

**Comment by Mikejmnez** [comment]
This issue is being addressed at the ```xarray``` level.
https://github.com/pydata/xarray/pull/4003#issue-408844574
