### ISSUE TITLE
Discussion: rioxarray.open_rasterio() in addition to xarray.open_rasterio()?

### ISSUE THREAD

**Issue by scottyhq** [intake/intake-xarray#87]
rioxarray is a nice library that extends xarray DataArrays for geospatial data.
https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html. It is much like the 'geopandas' equivalent for xarray.

Essentially it provides 1) `rioxarray.open_rasterio`, a drop-in replacement for `xarray.open_rasterio` with optimizations for `rasterio.open` and 2) extends returned DataArray objects for handling of geospatial data (coordinate reference system, reprojection in particular). This added functionality would be particularly valuable for intake-stac (https://github.com/intake/intake-stac)

My question is how to organize the option for `RasterIOSource` to use rioxarray instead of xarray? One path forward could be to create an option for the opener function? 
https://github.com/intake/intake-xarray/blob/bd43095c3f418aaf6f5cda0d3fbdf108243611e7/intake_xarray/image.py#L128

related: https://github.com/intake/intake-xarray/issues/61

**Comment by martindurant** [comment]
> One path forward could be to create an option for the opener function

Seems like a simple enough option.
Yes, there is scope for a larger discussion about these similar and somewhat interchangeable loaders, similar to some `engine=` kw, where each option has different capabilities and configuration. I don't know the best way to structure it, which is why this became what I thought of as the simplest approach :)

**Comment by aaronspring** [comment]
When rioxarray is installed xr now understands engine=rasterio. Does that solve the discussion @scottyhq ?

**Comment by aaronspring** [comment]
I suggest either to:
- get rid of https://github.com/intake/intake-xarray/blob/master/intake_xarray/raster.py and rewrite all `rasterio` tests with the netcdf driver: breaks `intake.open_rasterio`
- use the rasterio driver as a shortcut to `netcdf(engine="rasterio")`: keeps `intake.open_rasterio`

**Comment by martindurant** [comment]
I think indeed, the rasterio driver should become an alias for what is not netcdf; and maybe hey should all become just aliases for a generic xarray driver (including zarr?!). We should probably keep the current names and defaults at least for a while, though.

**Comment by aaronspring** [comment]
> the rasterio driver should become an alias for what is not netcdf

do you mean everything that is not opened by `xarray`?

> maybe hey should all become just aliases for a generic xarray driver (including zarr?!)

its `zarr` like `csv` supported by `intake`?

> We should probably keep the current names and defaults at least for a while, though.

definitely.

---

do you mean:
- `intake.open_xarray()` refactoring `intake.open_netcdf()`
- `intake.open_rasterio()` alias for `open_xarray(engine="rasterio")`
- `intake.open_zarr()` alias for `open_xarray(engine="zarr")`
- `intake.open_cfgrib()` alias for `open_xarray(engine="cfgrib")`
- `intake.open_something_else` alias for `current_rasterio_driver`?

**Comment by raybellwaves** [comment]
I'm thinking of an arg of `use_rioxarray` to `RasterIOSource` which defaults to True.

Had a quick tinker here: https://github.com/raybellwaves/intake-rioxarray/blob/main/intake_rioxarray/catalog.py#L79 as a separate plugin but it should be added.

**Comment by martindurant** [comment]
@raybellwaves , perhaps it's best just to put it in a PR, so we can see by the tests and docstrings how to use the various options in practice? I would tend towards @aaronspring 's set of aliases - but actually it doesn't matter much, so long as we are super clear in our description. Ideally, any change would be backwards compatible, by which I mean that existing catalogs continue to function.

**Comment by martindurant** [comment]
@raybellwaves , do you plan on making a PR like this?

**Comment by droumis** [comment]
[xarray v2023.04.0 removed the rasterio backend](https://github.com/pydata/xarray/releases/tag/v2023.04.0)

so `xr.open_rasterio` no longer works in [intake_xarray/raster.py](https://github.com/intake/intake-xarray/blob/03666211f0eff24d6f6f693be5a878e4bf5626e1/intake_xarray/raster.py).

**Comment by martindurant** [comment]
Fixed by #132
