### ISSUE TITLE
opendap driver option for netcdf4 engine / CEDA archive opendap access

### ISSUE THREAD

**Issue by larsbuntemeyer** [intake/intake-xarray#90]
**use case**
Hi, i got into some trouble when using `intake-xarray` with the CEDA(https://catalogue.ceda.ac.uk/uuid/89e1e34ec3554dc98594a5732622bce9) archive. CEDA uses SSL certificates that have to be created once per machine and normal `xarray.open_dataset` will work with opendap urls from CEDA.

script to create CEDA certificate: https://github.com/cedadev/opendap-python-example/blob/master/remote_nc_reader.py

**problem traceback**
However, with intake-xarray's opendap driver, it get SSL errors while normal `xarray.open_dataset` finds the certificate and just works fine. xarrays default engine for reading opendap is `netcdf4` while intake-xarray uses `pydap` by default (as far as I see).

**suggestion**
`intake-xarray` should mirror behavior from xarray.open_dataset and use `netcdf4` as an engine also for opendap access (if no session is required). According to http://xarray.pydata.org/en/stable/io.html#opendap it should be possible to choose at least...

THANKS!

**Comment by martindurant** [comment]
This looks related to https://github.com/intake/intake-xarray/pull/76

I didn't follow from your description: which source class are you using?

**Comment by larsbuntemeyer** [comment]
I use `OpenDapSource` source class.

**Comment by larsbuntemeyer** [comment]
Yes, this is related to #76. I am not sure why intake-xarray distinguishes between OPeNDAP and NetCDF4 in such a strict way anyway while xarray.open_dataset does not. As far as I understood, the `pydap` engine is used if explicit authentication is required. Maybe there should be only one `netcdf` driver that might have an `auth` argument that determines the backend of the source class.

**Comment by larsbuntemeyer** [comment]
Please be aware, that default engine for opendap is still `pydap` to ensure compatibility.
