### ISSUE TITLE
Document release process (and cut 0.4.1)

### ISSUE THREAD

**Issue by scottyhq** [intake/intake-xarray#95]
It would be great to get a new release (0.4.1) out. @martindurant - I'd be happy to add a small section in the docs regarding your preferred way to do this. 

Or we could add a ["publish" github action](https://github.com/intake/intake-stac/blob/master/.github/workflows/pypipublish.yaml) to push to pypi as we're doing in intake-stac that just requires pushing a new tag. A changelog would also be nice to add.

**Comment by martindurant** [comment]
> we could add a "publish" github action to push to pypi

Sounds like a good plan! I have still to get around to doing any GHaction myself.

The changelog could be generated from PR titles for now.

**Comment by weiji14** [comment]
Gentle nudge to see if we could we get a v0.4.1 tag for `intake-xarray` :slightly_smiling_face:

**Comment by scottyhq** [comment]
right, thanks @weiji14 i've been a bit busy lately and would be happy if you released a new version! Note that it's probably worth sorting this issue out and adding a test for the many file case https://github.com/intake/intake-xarray/issues/94#issuecomment-738883524

**Comment by weiji14** [comment]
Cool, I haven't got permissions on this repo but happy to get added to the team/organization here (and on PyPI?) to see what I can do for the release. The [changelog](https://github.com/intake/intake-xarray/blob/master/CHANGELOG.md#v041---2020-12-03) actually said the release was on 2020-12-03, should we update that?

The issue at #94 seems a bit complicated to write a test case for, and I'd suggest solving that in v0.4.2.

**Comment by scottyhq** [comment]
> should we update that? 
yep ;) 

Seems that I can't change repo permissions settings, @martindurant are you the only one currently with those permissions?

**Comment by martindurant** [comment]
I thought you could too @scottyhq , at a maintainer. I don't see a higher level of permissions. In any case, I have invited @weiji14 to that level too.

I'll add you both to pypi - do you both have the same usernames as on github?

**Comment by scottyhq** [comment]
> I'll add you both to pypi - do you both have the same usernames as on github? 
yes

**Comment by weiji14** [comment]
Yep, I have the same username on PyPI.

**Comment by martindurant** [comment]
You are both added as maintainers on pypi

**Comment by weiji14** [comment]
Great, I'll push a v0.4.1 tag and the PyPI publish workflow at https://github.com/intake/intake-xarray/blob/31cb241f5cc74b01bd5d399b0d8fc695acf4063a/.github/workflows/pypipublish.yaml should work :crossed_fingers:.

**Comment by weiji14** [comment]
Hmm, looking at https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#release, I think we need to change this line to use 'published' instead of 'created':

https://github.com/intake/intake-xarray/blob/31cb241f5cc74b01bd5d399b0d8fc695acf4063a/.github/workflows/pypipublish.yaml#L3-L5

**Comment by martindurant** [comment]
Feel free to use twine locally too... I have never bothered to click the "release" button in github anyway

**Comment by weiji14** [comment]
Haven't used twine before :joy:, I'll change the GitHub Actions workflow file and recreate a new v0.4.1 release...

**Comment by martindurant** [comment]
OK, whatever works for you!

**Comment by weiji14** [comment]
Ok, v0.4.1 is on PyPI at https://pypi.org/project/intake-xarray/0.4.1/ :smile:

**Comment by martindurant** [comment]
I'll merge the subsequent conda-forge PR when it comes through.

**Comment by weiji14** [comment]
Cool, happy to be added as a maintainer on https://github.com/conda-forge/intake-xarray-feedstock too.

**Comment by martindurant** [comment]
I think the easiest way is to make a PR adding you to the list of maintainers in the meta file
