### ISSUE TITLE
Error specifying `chunks=False` with `.to_dask()` when loading Zarr dataset on Pangeo Cloud

### ISSUE THREAD

**Issue by paigem** [intake/intake-xarray#97]
On Pangeo Cloud (intake version 0.6.0) when loading in a Zarr dataset, I am unable to set `chunks=False` while using `.to_dask()`. The code snippet below yields a `ZeroDivisionError`. However, a few weeks ago I was able to run this code successfully without error.

```python
import intake
cat = intake.open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/CESM_POP.yaml")
ds = cat['CESM_POP_hires_control'](chunks=False).to_dask()
```

<details><summary><tt>ZeroDivisionError</tt></summary>
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-38-09a3a7abfef2> in <module>
----> 1 ds = cat['CESM_POP_hires_control'](chunks=False).to_dask()
      2 #ds = ds.chunk({'time': 5})
      3 ds

/srv/conda/envs/notebook/lib/python3.8/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

/srv/conda/envs/notebook/lib/python3.8/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

/srv/conda/envs/notebook/lib/python3.8/site-packages/intake/source/base.py in _load_metadata(self)
    124         """load metadata only if needed"""
    125         if self._schema is None:
--> 126             self._schema = self._get_schema()
    127             self.datashape = self._schema.datashape
    128             self.dtype = self._schema.dtype

/srv/conda/envs/notebook/lib/python3.8/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

/srv/conda/envs/notebook/lib/python3.8/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, chunk_store, decode_timedelta, use_cftime, **kwargs)
    673     }
    674 
--> 675     ds = open_dataset(
    676         filename_or_obj=store,
    677         group=group,

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, autoclose, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables, backend_kwargs, use_cftime, decode_timedelta)
    573 
    574     with close_on_error(store):
--> 575         ds = maybe_decode_store(store, chunks)
    576 
    577     # Ensure source filename always stored in dataset object (GH issue #2550)

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py in maybe_decode_store(store, chunks)
    533                 chunks = dict.fromkeys(ds.dims, chunks)
    534 
--> 535             variables = {
    536                 k: _maybe_chunk(
    537                     k,

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/api.py in <dictcomp>(.0)
    534 
    535             variables = {
--> 536                 k: _maybe_chunk(
    537                     k,
    538                     v,

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py in _maybe_chunk(name, var, chunks, token, lock, name_prefix, overwrite_encoded_chunks)
    379         token2 = tokenize(name, token if token else var._data, chunks)
    380         name2 = f"{name_prefix}{name}-{token2}"
--> 381         var = var.chunk(chunks, name=name2, lock=lock)
    382 
    383         if overwrite_encoded_chunks and var.chunks is not None:

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/variable.py in chunk(self, chunks, name, lock)
   1051                 chunks = tuple(chunks.get(n, s) for n, s in enumerate(self.shape))
   1052 
-> 1053             data = da.from_array(data, chunks, name=name, lock=lock, **kwargs)
   1054 
   1055         return type(self)(self.dims, data, self._attrs, self._encoding, fastpath=True)

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask/array/core.py in from_array(x, chunks, name, lock, asarray, fancy, getitem, meta)
   2872     previous_chunks = getattr(x, "chunks", None)
   2873 
-> 2874     chunks = normalize_chunks(
   2875         chunks, x.shape, dtype=x.dtype, previous_chunks=previous_chunks
   2876     )

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask/array/core.py in normalize_chunks(chunks, shape, limit, dtype, previous_chunks)
   2559 
   2560     if chunks and shape is not None:
-> 2561         chunks = sum(
   2562             (
   2563                 blockdims_from_blockshape((s,), (c,))

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask/array/core.py in <genexpr>(.0)
   2561         chunks = sum(
   2562             (
-> 2563                 blockdims_from_blockshape((s,), (c,))
   2564                 if not isinstance(c, (tuple, list))
   2565                 else (c,)

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask/array/core.py in blockdims_from_blockshape(shape, chunks)
   1008     shape = tuple(map(int, shape))
   1009     chunks = tuple(map(int, chunks))
-> 1010     return tuple(
   1011         ((bd,) * (d // bd) + ((d % bd,) if d % bd else ()) if d else (0,))
   1012         for d, bd in zip(shape, chunks)

/srv/conda/envs/notebook/lib/python3.8/site-packages/dask/array/core.py in <genexpr>(.0)
   1009     chunks = tuple(map(int, chunks))
   1010     return tuple(
-> 1011         ((bd,) * (d // bd) + ((d % bd,) if d % bd else ()) if d else (0,))
   1012         for d, bd in zip(shape, chunks)
   1013     )

ZeroDivisionError: integer division or modulo by zero
</details>

The error occurs only when using both `(chunks=False)` and `.to_dask()` together; they do not error when used separately. However, I would like to be able to load the data without the preset chunking, and then rechunk myself manually, rather than loading in the already chunked dataset and then rechunking on top of that.

My understanding of intake is rather limited, but any help understanding this would be much appreciated!

**Comment by martindurant** [comment]
I wonder, does `xarray.open_zarr` (or `xarray.open_dataset(engine="zarr")` work correctly with `chunks=False`? Perhaps the correct value is `None`, or an empty dictionary?

**Comment by paigem** [comment]
Yep, looks like using either `chunks=None` or `chunks={}` solves the problem! Thanks @martindurant!
